# This file was auto-generated by `agentos init` on Sep 14, 2021 15:53:51.
import agentos
from stable_baselines3 import PPO


# A basic trainer
class BasicTrainer(agentos.Trainer):
    def init(self):
        self.sb3_ppo = PPO('MlpPolicy', self.environment)

    def improve(self, dataset, policy):
        self.sb3_ppo.learn()