# This file was auto-generated by `agentos init` on Dec 21, 2021 16:33:09.
import agentos


# A basic agent.
class BasicAgent(agentos.Agent):
    DEFAULT_ENTRY_POINT = "evaluate"
    def learn(self,
              num_episodes=10,
              test_every=True,
              test_num_episodes=5):
        """Set up some defaults params for this entry point."""
        super().learn(num_episodes,
                      test_every,
                      test_num_episodes)