# This file was auto-generated by `agentos init` on Feb 02, 2022 15:37:37.
import random


class RandomPolicy:
    def decide(self, observation):
        return random.choice(self.environment.action_space)
