# This file was auto-generated by `agentos init` on Feb 21, 2022 10:05:41.
import random


class RandomPolicy:
    def decide(self, observation):
        return random.choice(self.environment.action_space)
