# This file was auto-generated by `agentos init` on Feb 04, 2022 12:12:47.


class BasicTrainer:
    def train(self):
        transition_count = sum([len(e) for e in self.dataset.episodes])
        print("\nTrainer: dataset has", transition_count, "transitions")
        print("\tTrainer: No-op training policy", str(self.policy))
