# This file was auto-generated by `agentos init` on Feb 02, 2022 15:37:37.


class BasicTrainer:
    def train(self):
        transition_count = len(self.dataset.transitions)
        print("\nTrainer: dataset has", transition_count, "transitions")
        print("\tTrainer: No-op training policy", str(self.policy))
