# Generated by Django 3.2.7 on 2021-09-13 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("EN", "EN"),
                            ("PO", "PO"),
                            ("AG", "AG"),
                            ("DA", "DA"),
                            ("TR", "TR"),
                        ],
                        max_length=2,
                    ),
                ),
                ("description", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ComponentRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("git_hash", models.CharField(max_length=200)),
                ("github_url", models.CharField(max_length=200)),
                ("file_path", models.TextField()),
                ("class_name", models.CharField(max_length=200)),
                ("requirements_path", models.TextField()),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registry.component",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Agent",
        ),
        migrations.DeleteModel(
            name="Environment",
        ),
    ]
