# Generated by Django 3.2.11 on 2022-03-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runcommand',
            name='log_return_value',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
