# Generated by Django 3.2.11 on 2022-01-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="instantiate",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
