# Generated by Django 3.2.7 on 2021-11-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="componentdependency",
            old_name="alias",
            new_name="attribute_name",
        ),
    ]
