# Generated by Django 3.2.7 on 2021-09-14 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0002_auto_20210913_0604"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentrelease",
            name="component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="releases",
                to="registry.component",
            ),
        ),
    ]
