# Generated by Django 3.2.7 on 2021-09-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0003_alter_componentrelease_component"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
