# Generated by Django 3.2.11 on 2022-02-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0003_repo_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="repo",
            old_name="name",
            new_name="identifier",
        ),
    ]
