# Generated by Django 3.2.7 on 2021-09-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0004_alter_component_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "components",
                    models.ManyToManyField(
                        related_name="runs", to="registry.Component"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
