# Generated by Django 3.2.7 on 2021-09-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0005_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="agent_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="run",
            name="benchmark_data",
            field=models.JSONField(default=dict),
        ),
    ]
