# Generated by Django 3.2.11 on 2022-02-03 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0006_rename_github_url_repo_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="component",
            name="description",
        ),
    ]
