agent:
    evaluate:
        num_episodes: 50
    learn:
        num_episodes: 3
        test_every: True
        test_num_episodes: 1
dataset:
    __init__:
        max_replay_size: 500
        priority_exponent: 0.6
        max_priority_weight: 0.9
policy:
    __init__:
        epsilon: 0.01
trainer:
    __init__:
        learning_rate: 0.001
        adam_epsilon: 0.001
        burn_in_length: 2
        n_step: 5
        min_replay_size: 50
        importance_sampling_exponent: 0.2
        clip_grad_norm: null
        samples_per_insert: 32.0
__global__:
    backing_dir: .aos # shared by agent and policy
    # ---------------------------
    # Shared by dataset and trainer:
    # ---------------------------
    discount: 0.99
    sequence_length: 13
    store_lstm_state: true
    replay_period: 40
    batch_size: 32
