store_lstm_state: true
counter: null
discount: 0.99
target_update_period: 25
importance_sampling_exponent: 0.2
learning_rate: 0.001
adam_epsilon: 0.001
max_priority_weight: 0.9
samples_per_insert: 32.0
min_replay_size: 50
burn_in_length: 2
sequence_length: 13
max_replay_size: 500
replay_period: 40
batch_size: 32
n_step: 5
clip_grad_norm: null
trace_length: 10
priority_exponent: 0.6
