specs:
    local_dir:
        type: LocalRepo
        path: .

    virtual_env:
        type: VirtualEnv
        requirements_files:
            - type: Path
              relative_path: ./requirements.txt
              repo: spec:local_dir

    agent:
        type: Instance
        argument_set:
            type: ArgumentSet
            args:
                - spec:network
                - spec:environment
                - spec:AcmeRun
            kwargs:
                discount: .99
                batch_size: 10
                samples_per_insert: 2
                min_replay_size: 10
        instance_of:
            type: Class
            name: AcmeDQNAgent
            module:
                type: FileModule
                file_path: ./agent.py
                repo: spec:local_dir
                virtual_env: spec:virtual_env

    network:
        type: Instance
        argument_set:
            type: ArgumentSet
            args:
                - spec:environment
                - spec:AcmeRun
        instance_of:
            type: Class
            name: AcmeDQNNetwork
            module:
                type: FileModule
                repo: spec:local_dir
                file_path: ./network.py

    environment:
        type: Instance
        argument_set:
            type: ArgumentSet
            kwargs:
                discount: .99
        instance_of:
            type: Class
            name: CartPole
            module:
                type: FileModule
                repo: spec:local_dir
                file_path: ./environment.py

    AcmeRun:
        type: Class
        name: AcmeRun
        module:
            type: FileModule
            repo: spec:local_dir
            file_path: ./run.py

    evaluate_args:
        type: ArgumentSet
        kwargs:
            num_episodes: 100

    learn_args:
        type: ArgumentSet
        kwargs:
            num_episodes: 200
