specs:
    local_dir:
        type: LocalRepo
        path: .

    agent:
        type: Instance
        argument_set:
            type: ArgumentSet
            args:
                - spec:network
                - spec:environment
                - spec:AcmeRun
            kwargs:
                discount: .99
                batch_size: 10
                samples_per_insert: 2
                min_replay_size: 10
        instance_of:
            type: Class
            name: AcmeDQNAgent
            module:
                type: Module
                repo: spec:local_dir
                file_path: ./agent.py
                requirements_path: ./requirements.txt

    network:
        type: Instance
        argument_set:
            type: ArgumentSet
            kwargs:
                environment: spec:environment
                AcmeRun: spec:AcmeRun
        instance_of:
            type: Class
            name: AcmeDQNNetwork
            module:
                type: Module
                repo: spec:local_dir
                file_path: ./network.py

    environment:
        type: Instance
        argument_set:
            type: ArgumentSet
            kwargs:
                discount: .99
        instance_of:
            type: Class
            name: CartPole
            module:
                type: Module
                repo: spec:local_dir
                file_path: ./environment.py

    AcmeRun:
        type: Class
        name: AcmeRun
        module:
            type: Module
            repo: spec:local_dir
            file_path: ./run.py

    evaluate_args:
        type: ArgumentSet
        kwargs:
            num_episodes: 100

    learn_args:
        type: ArgumentSet
        kwargs:
            num_episodes: 200
