# This file was auto-generated by `agentos init` on Aug 09, 2021 09:12:37.
import agentos
from stable_baselines3 import PPO


# A random policy to be converted into a wrapper around SB3's PPOPolicy.
class PPOPolicy(agentos.Policy):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.sb3_ppo = PPO("MlpPolicy", self.environment)

    def decide(self, observation):
        return self.sb3_ppo.predict(self.curr_obs)[0]

    def improve(self, **kwargs):
        pass

    def observe(self, action, observation, reward, done, info):
        pass
