#!/bin/bash

set -eu

# One liner to find script dir https://stackoverflow.com/a/246128
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source "$SCRIPT_DIR/common"

PYTHONPATH="$ROOT_DIR" sphinx-build "$DOCUMENTATION_DIR" "$BUILD_DIR"

echo
echo "Docs built in $BUILD_DIR"
