#!/bin/bash

set -eu

# https://stackoverflow.com/a/246128
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_DIR="$SCRIPT_DIR/../../../"

CONTAINER_ID=`docker ps --filter="name=acme_r2d2" --format="{{.ID}}"`
echo "Running on container $CONTAINER_ID"

docker exec -it "$CONTAINER_ID" "/bin/bash"
