imports:
    - ./a2c_cartpole_args.yaml
specs:
    papag_agent_dir:
        type: LocalRepo
        path: .

    openai_gym:
        type: GitHubRepo
        url: git@github.com:openai/gym.git

    ikostrikov_papag:
        type: GitHubRepo
        url: git@github.com:ikostrikov/pytorch-a2c-ppo-acktr-gail.git

    mgbellemare_ale:
        type: GitHubRepo
        url: https://github.com/mgbellemare/Arcade-Learning-Environment.git

    papag_class:
        type: Class
        name: PAPAGAgent
        module:
            type: Module
            repo: spec:papag_agent_dir
            file_path: agent.py
            requirements_path: ./requirements.txt

    evaluation_args:
        type: ArgumentSet
        kwargs:
            lr: .0007
            clip_param: 0.2
            value_loss_coef: 0.5
            num_processes: 8
            num_steps: 5
            num_mini_batch: 32
            log_interval: 10
            entropy_coef: 0.01

    PAPAGRun:
        type: Class
        name: PAPAGRun
        module:
            type: Module
            repo: spec:papag_agent_dir
            file_path: papag_output.py

    AtariEnv:
        type: Class
        name: AtariEnv
        module:
            type: Module
            repo: spec:mgbellemare_ale
            file_path: ./src/gym/envs/atari/environment.py
            version: db3728264f382402120913d76c4fa0dc320ef59f

    CartPoleEnv:
        type: Class
        name: CartPoleEnv
        module:
            type: Module
            repo: spec:openai_gym
            file_path: ./gym/envs/classic_control/cartpole.py
            version: c755d5c35a25ab118746e2ba885894ff66fb8c43

    A2C_ACKTR:
        type: Class
        name: A2C_ACKTR
        module:
            type: Module
            repo: spec:ikostrikov_papag
            file_path: ./a2c_ppo_acktr/algo/a2c_acktr.py
            version: 41332b78dfb50321c29bade65f9d244387f68a60

    PPO:
        type: Class
        name: PPO
        module:
            type: Module
            repo: spec:ikostrikov_papag
            file_path: ./a2c_ppo_acktr/algo/ppo.py
            version: 41332b78dfb50321c29bade65f9d244387f68a60
