# https://github.com/ikostrikov/pytorch-a2c-ppo-acktr-gail#ppo
# python main.py --env-name "PongNoFrameskip-v4" --algo ppo --use-gae --lr 2.5e-4 --clip-param 0.1 --value-loss-coef 0.5 --num-processes 8 --num-steps 128 --num-mini-batch 4 --log-interval 1 --use-linear-lr-decay --entropy-coef 0.01



agent:
    evaluate:
        env_name: PongNoFrameskip-v4
        algo: ppo
        use_gae: True
        lr: .00025
        clip_param: 0.1
        value_loss_coef: 0.5
        num_processes: 8
        num_steps: 128
        num_mini_batch: 4
        log_interval: 1
        use_linear_lr_decay: True
        entropy_coef: 0.01
    learn:
        env_name: PongNoFrameskip-v4
        algo: ppo
        use_gae: True
        lr: .00025
        clip_param: 0.1
        value_loss_coef: 0.5
        num_processes: 8
        num_steps: 128
        num_mini_batch: 4
        log_interval: 1
        use_linear_lr_decay: True
        entropy_coef: 0.01
        num_env_steps: 25000
