# This workflow will install dependencies and run tests against various OSes and Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests on master

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  run_pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: Install agentos
        run: |
          pip install -e .
      - name: Run pytest
        run: |
          python -m pytest -k test_sb3 --durations=0 --ignore=tests/test_acme_from_registry.py --ignore=tests/example_agents/test_acme_r2d2.py
